name: QUAM pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"
        cache-dependency-path: pyproject.toml

    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Black formatting check
      run: poe check-format

    - name: Flake8 linting
      run: poe lint

    - name: Mypy type check
      run: poe typecheck

  run-tests:
    uses: ./.github/workflows/run_tests.yaml
    secrets: inherit
